server:
  port: 9001

spring:
  application:
    name: gateway-server

  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        # User-Crud
        - id: user-crud
          uri: lb://user
          predicates:
            - Path=/user/**

        # Pet-Crud
        - id: pet-crud
          uri: lb://pet
          predicates:
            - Path=/pet/**

        # Health
        - id: health
          uri: lb://pet
          predicates:
            - Path=/pet/**

        # Adoption
        - id: adoption
          uri: lb://pet
          predicates:
            - Path=/pet/**