server:
  port: 6666

spring:
  application:
    name: user-sender
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
      bootstrap-servers: localhost:9092
      group-id: ${spring.application.name}
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer

environment:
  user-topic: user

logging:
  level:
    ROOT: DEBUG
    io.confluent.kafka: DEBUG
    org.apache.kafka: DEBUG