server:
  port: 8990
spring:
  application:
    name: schema-registry-service
  cloud:
    stream:
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url:  http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
          brokers:
          - localhost:29092
      bindings:
        input:
          group: test-stream-group
          destination: test
          content-type: application/*+avro
        output:
          destination: test
          content-type: application/*+avro