server:
  port: 8080

spring:

  config:
    activate:
      on-profile: default

  application:
    name: budget-generator

  datasource:
    url: jdbc:mysql://budget-generator-db:3306/budget-generator-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    # Propiedades generales de Kafka
    properties:
      schema.registry.url: http://schema-registry:8084
      bootstrap.servers: kafka:29092

    # Consumimos de "activity" y "material"
  #    consumer:
  #      group-id: ${spring.application.name}
  #      auto-offset-reset: earliest
  #      properties:
  #        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  #        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  #
  #    # Producimos a "budget"
  #    producer:
  #      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  #      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              state.dir: /tmp
              commit.interval.ms: 100
              topology.optimization: all
              session.timeout.ms: 10000
              schema.registry.url: http://schema-registry:8084
              auto.register.schemas: true
              default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

logging:
  level:
    ROOT: DEBUG
    io.confluent.kafka: DEBUG
    org.apache.kafka: DEBUG