server:
  port: 8080

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  config:
    activate:
      on-profile: default

  application:
    name: user-crud
    zipkin: http://zipkin:9411

  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5434/user_db
    username: postgres
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

resilience4j:
  circuitbreaker:
    configs:
      shared:
        sliding-window-type: count_based #Basado en contador
        sliding-window-size: 5 #Número de llamadas fallidas permitidas
        slow-call-rate-threshold: 50 #Porcentaje que vamos a permitir de llamadas fallidas o lentas
        permitted-number-of-calls-in-half-open-state: 1 #Número de llamadas permitidas en el estado medio abierto
        max-wait-duration-in-half-open-state: 10s #Tiempo de duración máximo del estado medio abierto
        wait-duration-in-open-state: 10s #Tiempo duración estado abierto
        writable-stack-trace-enabled: true #Logs por consola
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      user-crud:
        base-config: shared

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
