server:
  port: 8080

spring:
  application:
    name: user-validator

  kafka:
    # Consumimos de "user"
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://schema-registry:8084
        bootstrap.servers: kafka:29092
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

    # Producimos a "user_validated"
    producer:
      properties:
        schema.registry.url: http://schema-registry:8084
        bootstrap.servers: kafka:29092
        key-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer

logging:
  level:
    ROOT: DEBUG
    io.confluent.kafka: DEBUG
    org.apache.kafka: DEBUG